### ISSUE TITLE
backslash issue for path assignment in R (Windows)

### ISSUE THREAD

**Issue by kvdylla** [ejhonglab/hong2p#2]
I think the last (automatically generated) slash in the path should be a forward slash under Windows. Easiest solution to keep it working for both Windows and Ubuntu might be to add the slash in R and not in the python script.

<img width="715" alt="snapshot" src="https://user-images.githubusercontent.com/37002750/120127931-a9db7b80-c175-11eb-9183-1f978ad9838b.PNG">

**Comment by tom-f-oconnell** [comment]
![image](https://user-images.githubusercontent.com/22155564/120370368-5aa65f80-c2c9-11eb-8059-aa56026cc796.png)

**Comment by tom-f-oconnell** [comment]
Use two backslashes instead of single forward slashes in paths in R. Do not put slashes before the drive letter though. For instance:
```
thorimage_dir <- "D:\\data\\PNterminals_for_R\\20210508_a\\1_water"
```
